### PR TITLE
Update description field to take any prop

### PR DESCRIPTION
**Pull request by maxlew**
This update allows the description prop in ImageWithHeaderAndContent to take any value.

Note: this PR causes the custom styling that was previously on the `<Paragraph>` element to be lost.

### CODE REVIEW

**Comment by beau-charman** [comment]
Thank you for picking this up Max

**Comment by beau-charman** [comment]
In regards to the <p /> styling, you can use ParagraphSet https://github.com/aesop/aesop-gel/blob/develop/src/components/Paragraph/Paragraph.js#L24 to wrap any child <p /> tags in GEL styling. 

Also merge conflict.

**Comment by maxlew** [comment]
@beau-charman good point about the Paragraph. I'll use that as a wrapper to control styling. Happy to merge this now if you are.

**Comment by beau-charman** [comment]
👍

**Pull request merged**
