### PR TITLE
feat: publish npm package on push to main branch

### PR DESCRIPTION
**Pull request by gssumesh**
### Description: 
Publish npm package on commit to `main` branch. Updated package name to be a scoped package. This should not break existing process of referring to github commit id.

### Changes:
`.npmrc`: Set the npm package as public.
`push.yml`: Added npm token for publishing.
`.releaserc`: Added semantic package for npm which helps with publishing.
`package.json`: Added new package into package to support semantic releasing.

### CODE REVIEW

**Review by MkMan — APPROVED** [review]
Nice 👌  Any chance we can remove `/dist` from source control? It clutters the PRs

**Comment by gssumesh** [comment]
> Nice 👌 Any chance we can remove `/dist` from source control? It clutters the PRs

Did this one had dist changes? I cant see it @MkMan

**Comment by MkMan** [comment]
> 
> 
> > Nice 👌 Any chance we can remove `/dist` from source control? It clutters the PRs
> 
> Did this one had dist changes? I cant see it @MkMan

No, this PR didn't but others in the future will unless we add `dist` to git ignore and remove it from the git history 🙂

**Comment by andrwchang** [comment]
we need to make the subsequent changes on aesop-web-ui to use the npm package after this.

**Review by andrwchang — APPROVED** [review]

**Pull request merged**
