### PR TITLE
Add npm script to count remaining JS files

### PR DESCRIPTION
**Pull request by MkMan**
Not sure if this is worth it. I added it locally to see how many JS files are left and thought I'd raise a PR in case the team sees benefit in it.

image

### CODE REVIEW

**Comment by kevin-ho87** [comment]
What does it mean by files that are left?

**Comment by MkMan** [comment]
> What does it mean by files that are left?

We're in the process of migrating from `.js` to `.ts` | `.tsx`. I just thought this could help in seeing how many `.js` files are left in the repo 🙂

**Comment by kevin-ho87** [comment]
> > What does it mean by files that are left?
> 
> We're in the process of migrating from `.js` to `.ts` | `.tsx`. I just thought this could help in seeing how many `.js` files are left in the repo 🙂
> 
> Edit: I just realised the original PR description had a typo and it wasn't clear which files. I updated it now :)

Ah, makes sense. 👍

**Review by kevin-ho87 — APPROVED** [review]

**Review by beau-charman — APPROVED** [review]
cool idea 🙌

**Pull request merged**
