### PR TITLE
feat: updated the readme to make the link work with the correct npm r…

### PR DESCRIPTION
**Pull request by andrwchang**
running `npm link aesop-gel` from aesop-web-ui does not work as there is no npm registry exists with that name.
updated to point to the correct npm registry

### CODE REVIEW

**Comment by zack76** [comment]
I think this one hasn't been merged yet
https://github.com/aesop/aesop-web-ui/pull/4024

**Comment by andrwchang** [comment]
@zack76 This can go in as this is only the change in readme to fix the issue in dev.

**Review by zack76 — APPROVED** [review]

**Comment by hassanraza0054** [comment]
Keen to get thoughts on this PR @maxlew 

As @zack76 mentioned, can we drop this in favour of merging aesop/aesop-web-ui#4024 and documenting the new process in the readme instead?

**Comment by MkMan** [comment]
Is this PR still needed, @andrwchang ?

**Pull request closed without merging**
